export type IconName =
	| 'under-construction'
	| 'blank-canvas'
	| 'logo-github'
	| 'logo-linkedin'
	| 'node'
	| 'react'
	| 'svelte'
	| 'typescript'
	| 'open'
	| 'calendar'
	| 'pricetags'
	| 'person-circle-outline'
	| 'undraw-interview'
	| 'arrow-back-outline'
	| 'email-filled'
	| 'launch';
